version: '3'

services:
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    env_file:
      - ./redis/.env
    volumes:
      - ./redis/.data:/data
      - ./redis/config/redis.conf:/usr/local/etc/redis.conf
      - ./redis/logs.log:/var/log/redis/redis-server.log
    command: [redis-server, /usr/local/etc/redis.conf]

networks:
  auth:
    driver: bridge# networks:
